  device: cpu
  learn_every: 10
  learn_detection_every: 20
  add_image_every: 5
  batch_size: 64
  image_batch_size: 128
  buffer_size: 10_000
  image_buffer_size: 10_000
  epsilon: 
    start_value: .5
    end_value: .01
    steps: 1000