  device: cpu
  learn_every: 10
  learn_detection_every: 20
  add_image_every: 5
  gamma: 0.99
  tau: 0.1
  batch_size: 64
  image_batch_size: 128
  buffer_size: 10_000
  image_buffer_size: 4_000
  epsilon: 
    start_value: .5
    end_value: .01
    steps: 200_000
  network:
    body:
      type: "conv"
      input_size: 84
    head:
      type: "qnet"
      hidden_layers: [128, 64]
      learning_rate: .0002
      learning_rate_image: .0002